/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisProgress: typeof import('./../components/investigation/AnalysisProgress.vue')['default']
    AnalysisTimeLineChart: typeof import('./../components/visualization/AnalysisTimeLineChart.vue')['default']
    BarChart: typeof import('./../components/charts/BarChart.vue')['default']
    BaseChart: typeof import('./../components/charts/BaseChart.vue')['default']
    CaseCard: typeof import('./../components/investigation/CaseCard.vue')['default']
    ClueDetailPanel: typeof import('./../components/investigation/ClueDetailPanel.vue')['default']
    ClueGraph: typeof import('./../components/graph/ClueGraph.vue')['default']
    CountUp: typeof import('./../components/common/CountUp.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ErrorBoundary: typeof import('./../components/common/ErrorBoundary.vue')['default']
    EvidenceFilterPanel: typeof import('./../components/evidence/EvidenceFilterPanel.vue')['default']
    EvidenceGraph: typeof import('./../components/evidence/EvidenceGraph.vue')['default']
    EvidencePanel: typeof import('./../components/evidence/EvidencePanel.vue')['default']
    EvidenceTimeline: typeof import('./../components/evidence/EvidenceTimeline.vue')['default']
    FileCard: typeof import('./../components/investigation/FileCard.vue')['default']
    FormatAmount: typeof import('./../components/common/FormatAmount.vue')['default']
    FormatTime: typeof import('./../components/common/FormatTime.vue')['default']
    FundFlowGraphChart: typeof import('./../components/visualization/FundFlowGraphChart.vue')['default']
    GraphView: typeof import('./../components/graph/GraphView.vue')['default']
    LineChart: typeof import('./../components/charts/LineChart.vue')['default']
    Permission: typeof import('./../components/Permission.vue')['default']
    PieChart: typeof import('./../components/charts/PieChart.vue')['default']
    PortraitBehaviorPanel: typeof import('./../components/portrait/PortraitBehaviorPanel.vue')['default']
    PortraitCluesPanel: typeof import('./../components/portrait/PortraitCluesPanel.vue')['default']
    PortraitEconomicPanel: typeof import('./../components/portrait/PortraitEconomicPanel.vue')['default']
    PortraitSocialPanel: typeof import('./../components/portrait/PortraitSocialPanel.vue')['default']
    ReportSection: typeof import('./../components/investigation/ReportSection.vue')['default']
    RiskFactorChart: typeof import('./../components/investigation/RiskFactorChart.vue')['default']
    RiskScoreGauge: typeof import('./../components/investigation/RiskScoreGauge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./../components/investigation/StatCard.vue')['default']
    StatusTag: typeof import('./../components/common/StatusTag.vue')['default']
    StepIndicator: typeof import('./../components/investigation/StepIndicator.vue')['default']
    TripHeatmapChart: typeof import('./../components/visualization/TripHeatmapChart.vue')['default']
    VirtualTable: typeof import('./../components/table/VirtualTable.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
